/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/common/about': RouteRecordInfo<
      '/common/about',
      '/common/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/iframe/': RouteRecordInfo<
      '/iframe/',
      '/iframe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options/': RouteRecordInfo<
      '/options/',
      '/options',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/popup/': RouteRecordInfo<
      '/popup/',
      '/popup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/': RouteRecordInfo<
      '/setup/',
      '/setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/install': RouteRecordInfo<
      '/setup/install',
      '/setup/install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/update': RouteRecordInfo<
      '/setup/update',
      '/setup/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/about.vue': {
      routes:
        | '/common/about'
      views:
        | never
    }
    'src/content-script/iframe/pages/index.vue': {
      routes:
        | '/iframe/'
      views:
        | never
    }
    'src/options/pages/index.vue': {
      routes:
        | '/options/'
      views:
        | never
    }
    'src/popup/pages/index.vue': {
      routes:
        | '/popup/'
      views:
        | never
    }
    'src/setup/pages/index.vue': {
      routes:
        | '/setup/'
      views:
        | never
    }
    'src/setup/pages/install.vue': {
      routes:
        | '/setup/install'
      views:
        | never
    }
    'src/setup/pages/update.vue': {
      routes:
        | '/setup/update'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
